import mongoose from 'mongoose';

/**
 * The append-only message log.
 *
 * Messages are never updated in place (edits and deletes are soft), never joined,
 * and always read by the same key: conversation + a sequence range. That is a log,
 * not a relation — which is why it lives in Mongo rather than Postgres.
 *
 * This collection is also the offline queue. There is no separate queue table:
 * everything with `seq > member.lastDeliveredSeq` is, by definition, undelivered.
 */
const messageSchema = new mongoose.Schema(
  {
    /** Postgres conversation uuid, stored as a string value (not a DBRef). */
    conversationId: { type: String, required: true },

    /** Allocated by Postgres. Monotonic per conversation, but NOT contiguous. */
    seq: { type: Number, required: true },

    /** Postgres user uuid, stored as a string value. */
    senderId: { type: String, required: true },

    /** uuid v4 generated by the browser — the idempotency key. */
    clientMsgId: { type: String, required: true },

    body: { type: String, required: true, maxlength: 4000 },
    contentType: { type: String, enum: ['text', 'system'], default: 'text' },

    createdAt: { type: Date, default: Date.now },
    editedAt: { type: Date, default: null },
    deletedAt: { type: Date, default: null },
  },
  { versionKey: false },
);

/**
 * The index. Serves both history pagination (seq < cursor, descending) and the
 * reconnect backlog drain (seq > watermark, ascending).
 */
messageSchema.index({ conversationId: 1, seq: -1 });

/**
 * What turns at-least-once delivery into an exactly-once *effect*. A retried send
 * carries the same clientMsgId and hits E11000 instead of writing a duplicate;
 * the handler then returns the already-stored document.
 */
messageSchema.index({ senderId: 1, clientMsgId: 1 }, { unique: true });

// Optional 90-day retention. Left commented because it deletes data — enable
// deliberately, not by accident.
// messageSchema.index({ createdAt: 1 }, { expireAfterSeconds: 7776000 });

export const Message = mongoose.model('Message', messageSchema);
